version: "3.8"

services:
  app:
    build: .
    container_name: zxzone-bot
    command: bash start.sh
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Dhaka
      PORT: 8080
      BOT_TOKEN: ${BOT_TOKEN}
      OWNER_ID: ${OWNER_ID}
      TELEGRAM_API: ${TELEGRAM_API}
      TELEGRAM_HASH: ${TELEGRAM_HASH}
      DATABASE_URL: ${DATABASE_URL}
      UPSTREAM_REPO: ${UPSTREAM_REPO}
      UPSTREAM_BRANCH: ${UPSTREAM_BRANCH}
      BASE_URL: ${BASE_URL}
    volumes:
      - ./downloads:/app/downloads
      - ./accounts:/app/accounts
      - ./logs:/app/logs
