name: Deploy ZxZone-Master-MLTB to Heroku

on:
  workflow_dispatch:
    inputs:
      HEROKU_APP_NAME:
        description: "Heroku App name"
        required: true
      HEROKU_API_KEY:
        description: "Heroku API key"
        required: true
      HEROKU_EMAIL:
        description: "Heroku email address"
        required: true
      HEROKU_STACK:
        description: "Heroku Stack (24 or 26)"
        required: true
        default: "24"
      BOT_TOKEN:
        description: "Telegram bot token"
        required: true
      OWNER_ID:
        description: "Owner's telegram ID"
        required: true
      DATABASE_URL:
        description: "Database URL from MongoDB"
        required: true
      TELEGRAM_API:
        description: "Telegram API ID"
        required: true
      TELEGRAM_HASH:
        description: "Telegram HASH"
        required: true
      UPSTREAM_REPO:
        description: "Upstream Repo Link"
        required: true
        default: "https://github.com/obscure-n8/ZxZone-Master-MLTB"
      UPSTREAM_BRANCH:
        description: "Upstream Branch"
        required: true
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Set Container Stack
        run: |
          heroku stack:set container -a ${{ inputs.HEROKU_APP_NAME }} --force
        env:
          HEROKU_API_KEY: ${{ inputs.HEROKU_API_KEY }}

      - name: Deploy to Heroku (Git Push)
        run: |
          heroku git:remote -a ${{ inputs.HEROKU_APP_NAME }}
          git push heroku main --force
        env:
          HEROKU_API_KEY: ${{ inputs.HEROKU_API_KEY }}

      - name: Set Config Vars
        run: |
          heroku config:set STACK_VERSION=${{ inputs.HEROKU_STACK }} -a ${{ inputs.HEROKU_APP_NAME }}
          heroku config:set OWNER_ID=${{ inputs.OWNER_ID }} -a ${{ inputs.HEROKU_APP_NAME }}
          heroku config:set TELEGRAM_API=${{ inputs.TELEGRAM_API }} -a ${{ inputs.HEROKU_APP_NAME }}
          heroku config:set TELEGRAM_HASH=${{ inputs.TELEGRAM_HASH }} -a ${{ inputs.HEROKU_APP_NAME }}
          heroku config:set DATABASE_URL=${{ inputs.DATABASE_URL }} -a ${{ inputs.HEROKU_APP_NAME }}
          heroku config:set BOT_TOKEN=${{ inputs.BOT_TOKEN }} -a ${{ inputs.HEROKU_APP_NAME }}
          heroku config:set UPSTREAM_REPO=${{ inputs.UPSTREAM_REPO }} -a ${{ inputs.HEROKU_APP_NAME }}
          heroku config:set UPSTREAM_BRANCH=${{ inputs.UPSTREAM_BRANCH }} -a ${{ inputs.HEROKU_APP_NAME }}
          heroku config:set BASE_URL=https://${{ inputs.HEROKU_APP_NAME }}.herokuapp.com -a ${{ inputs.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ inputs.HEROKU_API_KEY }}
